
# BEGIN_KITTY_FONTS
font_family      family="BigBlueTerm437 Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS


background_opacity 0.95

#: The basic colors

foreground                      #ffccf7
background                      #120117
selection_foreground            #120117
selection_background            #fdd0f6


#: Cursor colors

cursor                          #ac3232
cursor_text_color               #111111


#: URL underline color when hovering with mouse

url_color                       #2ee7b6


#: kitty window border colors and terminal bell colors

#active_border_color             #00ff00
#inactive_border_color           #cccccc
#bell_border_color               #ff5a00
#visual_bell_color               none


#: OS Window titlebar colors

#wayland_titlebar_color          system
#macos_titlebar_color            system


#: Tab bar colors

#active_tab_foreground           #141d2b
#active_tab_background           #9fef00
#inactive_tab_foreground         #141d2b
#inactive_tab_background         #a4b1cd
#tab_bar_background              none
#tab_bar_margin_color            none


#: Colors for marks (marked text in the terminal)

mark1_foreground black
mark1_background #9fef00
mark2_foreground black
mark2_background #9fef00
mark3_foreground black
mark3_background #9fef00


#: The basic 16 colors

#: black
color0 #000000
color8 #767676

#: red
color1 #dd48f7
color9 #ff74f8

#: green
color2  #158157
color10 #1eb574

#: yellow
color3  #734878
color11 #bb55e6

#: blue
color4  #336be5
color12 #6ac0f1

#: magenta
color5  #bb56b1
color13 #d286ca

#: cyan
color6  #0ba4a4
color14 #15f9f9

#: white
color7  #dddddd
color15 #ffffff